/**
 * A small, dependency-free Markdown parser.
 *
 * Why not `react-markdown` / `marked`?
 *
 * `package-lock.json` is not shipped in the release archive, and the Docker
 * build runs `npm ci`, which fails hard when `package.json` lists a package the
 * lockfile does not contain. Adding a Markdown dependency here would therefore
 * break the Railway build until the lockfile was regenerated by hand. A blog
 * body needs headings, lists, links, quotes and code fences -- roughly ninety
 * lines of parsing -- so the dependency is not worth a broken deploy.
 *
 * The parser emits a plain token tree. It never emits HTML strings, so the
 * renderer never needs `dangerouslySetInnerHTML` and post bodies cannot inject
 * markup. That is the main security property of this module: an admin who
 * pastes `<script>` into a post gets literal text, not a script tag.
 */

export type InlineToken =
	| { type: "text"; value: string }
	| { type: "bold"; value: string }
	| { type: "italic"; value: string }
	| { type: "code"; value: string }
	| { type: "link"; value: string; href: string }

export type MarkdownBlock =
	| { type: "heading"; level: 2 | 3 | 4; text: InlineToken[]; id: string }
	| { type: "paragraph"; text: InlineToken[] }
	| { type: "list"; ordered: boolean; items: InlineToken[][] }
	| { type: "quote"; text: InlineToken[] }
	| { type: "code"; lang: string | null; value: string }
	| { type: "image"; src: string; alt: string }
	| { type: "divider" }

/* ------------------------------------------------------------------ *
 * Links
 * ------------------------------------------------------------------ */

/**
 * Only absolute http(s), mailto and site-relative links survive.
 *
 * Without this, `[click](javascript:alert(1))` would render a working XSS
 * vector straight out of the admin editor. Anything unrecognised degrades to
 * `#`, which is inert but keeps the link text visible.
 */
export function safeHref(href: string): string {
	const value = href.trim()
	if (value.startsWith("/") || value.startsWith("#")) return value
	if (/^https?:\/\//i.test(value)) return value
	if (/^mailto:/i.test(value)) return value
	if (/^tel:/i.test(value)) return value
	return "#"
}

/* ------------------------------------------------------------------ *
 * Inline parsing
 * ------------------------------------------------------------------ */

// Order matters: `**` must be tried before `*`, otherwise bold is read as two
// empty italics. Inline code is matched first so that markers inside a code
// span stay literal.
const INLINE_PATTERN =
	/(`[^`]+`)|(\[[^\]]+\]\([^)\s]+\))|(\*\*[^*]+\*\*)|(\*[^*]+\*)/g

export function parseInline(input: string): InlineToken[] {
	const tokens: InlineToken[] = []
	let lastIndex = 0

	for (const match of input.matchAll(INLINE_PATTERN)) {
		const index = match.index ?? 0
		if (index > lastIndex) {
			tokens.push({ type: "text", value: input.slice(lastIndex, index) })
		}

		const chunk = match[0]
		if (chunk.startsWith("`")) {
			tokens.push({ type: "code", value: chunk.slice(1, -1) })
		} else if (chunk.startsWith("[")) {
			const split = chunk.indexOf("](")
			tokens.push({
				type: "link",
				value: chunk.slice(1, split),
				href: safeHref(chunk.slice(split + 2, -1)),
			})
		} else if (chunk.startsWith("**")) {
			tokens.push({ type: "bold", value: chunk.slice(2, -2) })
		} else {
			tokens.push({ type: "italic", value: chunk.slice(1, -1) })
		}

		lastIndex = index + chunk.length
	}

	if (lastIndex < input.length) {
		tokens.push({ type: "text", value: input.slice(lastIndex) })
	}

	return tokens
}

/* ------------------------------------------------------------------ *
 * Headings
 * ------------------------------------------------------------------ */

/**
 * Slugifies a heading into an anchor id.
 *
 * Cyrillic is transliterated rather than stripped: posts are written in Uzbek
 * and Russian, and stripping non-Latin characters would collapse every Russian
 * heading to an empty id, making all of them collide.
 */
const CYRILLIC: Record<string, string> = {
	а: "a",
	б: "b",
	в: "v",
	г: "g",
	д: "d",
	е: "e",
	ё: "e",
	ж: "zh",
	з: "z",
	и: "i",
	й: "y",
	к: "k",
	л: "l",
	м: "m",
	н: "n",
	о: "o",
	п: "p",
	р: "r",
	с: "s",
	т: "t",
	у: "u",
	ф: "f",
	х: "h",
	ц: "c",
	ч: "ch",
	ш: "sh",
	щ: "sch",
	ъ: "",
	ы: "y",
	ь: "",
	э: "e",
	ю: "yu",
	я: "ya",
}

export function slugifyHeading(input: string): string {
	const latin = input
		.toLowerCase()
		.split("")
		.map((char) => CYRILLIC[char] ?? char)
		.join("")

	const slug = latin
		.replace(/[^a-z0-9\s-]/g, "")
		.trim()
		.replace(/\s+/g, "-")
		.slice(0, 60)

	return slug || "bolim"
}

/* ------------------------------------------------------------------ *
 * Block parsing
 * ------------------------------------------------------------------ */

const LIST_ITEM = /^[-*]\s+(.*)$/
const ORDERED_ITEM = /^\d+[.)]\s+(.*)$/
const IMAGE_ONLY = /^!\[([^\]]*)\]\(([^)\s]+)\)$/

export function parseMarkdown(source: string): MarkdownBlock[] {
	if (!source) return []

	// Normalise line endings first. Content pasted from Windows carries \r\n,
	// and a trailing \r makes every regex below miss its anchor.
	const lines = source.replace(/\r\n?/g, "\n").split("\n")
	const blocks: MarkdownBlock[] = []

	let paragraph: string[] = []
	const usedIds = new Set<string>()

	const flushParagraph = () => {
		if (paragraph.length === 0) return
		blocks.push({ type: "paragraph", text: parseInline(paragraph.join(" ")) })
		paragraph = []
	}

	// Duplicate headings would otherwise produce duplicate DOM ids, which breaks
	// both anchor links and accessibility tooling.
	const uniqueId = (text: string) => {
		const base = slugifyHeading(text)
		if (!usedIds.has(base)) {
			usedIds.add(base)
			return base
		}
		let suffix = 2
		while (usedIds.has(`${base}-${suffix}`)) suffix += 1
		const id = `${base}-${suffix}`
		usedIds.add(id)
		return id
	}

	for (let index = 0; index < lines.length; index += 1) {
		const line = lines[index] ?? ""
		const trimmed = line.trim()

		// --- fenced code -------------------------------------------------
		if (trimmed.startsWith("```")) {
			flushParagraph()
			const lang = trimmed.slice(3).trim() || null
			const body: string[] = []
			index += 1
			while (
				index < lines.length &&
				!(lines[index] ?? "").trim().startsWith("```")
			) {
				body.push(lines[index] ?? "")
				index += 1
			}
			blocks.push({ type: "code", lang, value: body.join("\n") })
			continue
		}

		if (trimmed === "") {
			flushParagraph()
			continue
		}

		if (/^(-{3,}|\*{3,}|_{3,})$/.test(trimmed)) {
			flushParagraph()
			blocks.push({ type: "divider" })
			continue
		}

		const image = IMAGE_ONLY.exec(trimmed)
		if (image) {
			flushParagraph()
			blocks.push({
				type: "image",
				alt: image[1] ?? "",
				src: safeHref(image[2] ?? ""),
			})
			continue
		}

		const heading = /^(#{1,6})\s+(.*)$/.exec(trimmed)
		if (heading) {
			flushParagraph()
			const raw = (heading[2] ?? "").trim()
			// H1 is reserved for the post title rendered by the page, so an H1 in
			// the body is demoted to H2 rather than competing with it.
			const depth = (heading[1] ?? "#").length
			const level = depth <= 2 ? 2 : depth === 3 ? 3 : 4
			blocks.push({
				type: "heading",
				level,
				text: parseInline(raw),
				id: uniqueId(raw),
			})
			continue
		}

		if (trimmed.startsWith("> ")) {
			flushParagraph()
			const quote: string[] = [trimmed.slice(2)]
			while (
				index + 1 < lines.length &&
				(lines[index + 1] ?? "").trim().startsWith("> ")
			) {
				index += 1
				quote.push((lines[index] ?? "").trim().slice(2))
			}
			blocks.push({ type: "quote", text: parseInline(quote.join(" ")) })
			continue
		}

		// --- lists ---------------------------------------------------------
		const bullet = LIST_ITEM.exec(trimmed)
		const ordered = ORDERED_ITEM.exec(trimmed)
		if (bullet || ordered) {
			flushParagraph()
			const isOrdered = Boolean(ordered)
			const items: InlineToken[][] = [
				parseInline(((isOrdered ? ordered?.[1] : bullet?.[1]) ?? "").trim()),
			]

			while (index + 1 < lines.length) {
				const next = (lines[index + 1] ?? "").trim()
				const nextMatch = isOrdered
					? ORDERED_ITEM.exec(next)
					: LIST_ITEM.exec(next)
				if (!nextMatch) break
				items.push(parseInline((nextMatch[1] ?? "").trim()))
				index += 1
			}

			blocks.push({ type: "list", ordered: isOrdered, items })
			continue
		}

		paragraph.push(trimmed)
	}

	flushParagraph()
	return blocks
}

/* ------------------------------------------------------------------ *
 * Reading time
 * ------------------------------------------------------------------ */

/**
 * Estimates reading minutes from the body text.
 *
 * `Post.readMinutes` is an admin-editable column with a default of 3, so it is
 * treated as an override: when the author sets it, it wins; otherwise this
 * estimate is used. 180 wpm is the conservative end for technical prose, which
 * suits posts full of code and product names.
 */
export function estimateReadMinutes(source: string): number {
	const words = source
		.replace(/```[\s\S]*?```/g, " ")
		.replace(/[#>*`_[\]()!-]/g, " ")
		.split(/\s+/)
		.filter(Boolean).length

	return Math.max(1, Math.round(words / 180))
}

/** Plain text for meta descriptions and excerpts. */
export function toPlainText(source: string, limit = 180): string {
	const text = source
		.replace(/```[\s\S]*?```/g, " ")
		.replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
		.replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
		.replace(/[#>*`_]/g, "")
		.replace(/\s+/g, " ")
		.trim()

	if (text.length <= limit) return text
	return `${text.slice(0, limit).trimEnd()}…`
}
